version: "3.7"
services:

  ddl:
    build: ddl 
    container_name: tro_ddl
    restart: "no"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    secrets:
      - db-password
    networks:
      - pgpods-network 
    volumes:
      - /Users/Jeff/devl/tro/local/log/:/home/container/tro/local/log/

secrets:
  db-password:
    file: ./.secrets-db-password

networks:
  pgpods-network:
    external: true
    
    