version: "3.7"
services:

  ddl:
    build: ddl 
    restart: "no"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    secrets:
      - db-password
    networks:
      - pgpods-network 
    volumes:
      - /Users/Jeff/devl/trorpts/local/rpt/:/home/container/trorpts/local/rpt/

secrets:
  db-password:
    file: ./.secrets-db-password

networks:
  pgpods-network:
    external: true
    
    
