version: "3.7"
services:

  db:
    build: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/opt/app/postgres/data
    networks:
      - backend-network
    environment:
      - PGDATABASE=pgdb

  app:
    build: app
    restart: always
    secrets:
      - db-password
    networks:
      - backend-network
      - frontend-network
    volumes:
      - ./app/src:/code

  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontend-network

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backend-network:
  frontend-network:
