version: "3"
services:

#   ddl:
#     build: ./ddl 
#    container_name: tro_ddl
#     restart: "no"
#     environment:
#       - ENVIRONMENT=${ENVIRONMENT}
#     secrets:
#       - db-password
#     networks:
#       - pgpods-network 
#     volumes:
#       - /Users/Jeff/devl/tro/local/log/:/home/container/tro/local/log/

  flask_app:
    build: ./tro_flask_app
    container_name: tro_flask_app
    restart: always
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - flask_app

secrets:
  db-password:
    file: ./.secrets-db-password

# networks:
#   pgpods-network:
#     external: true
    
